/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_mattsutter_conditionred_RadarRenderer */

#ifndef _Included_me_mattsutter_conditionred_RadarRenderer
#define _Included_me_mattsutter_conditionred_RadarRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_mattsutter_conditionred_RadarRenderer
 * Method:    initAnimation
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_me_mattsutter_conditionred_RadarRenderer_initAnimation
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     me_mattsutter_conditionred_RadarRenderer
 * Method:    DeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_me_mattsutter_conditionred_RadarRenderer_DeInit
  (JNIEnv *, jclass);

/*
 * Class:     me_mattsutter_conditionred_RadarRenderer
 * Method:    drawImage
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_me_mattsutter_conditionred_RadarRenderer_drawImage
  (JNIEnv *, jclass, jint);

/*
 * Class:     me_mattsutter_conditionred_RadarRenderer
 * Method:    bufferFrame
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_me_mattsutter_conditionred_RadarRenderer_bufferFrame
  (JNIEnv *, jclass, jint);

/*
 * Class:     me_mattsutter_conditionred_RadarRenderer
 * Method:    unbufferFrame
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_me_mattsutter_conditionred_RadarRenderer_unbufferFrame
  (JNIEnv *, jclass, jint);

/*
 * Class:     me_mattsutter_conditionred_RadarRenderer
 * Method:    changeAlpha
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_me_mattsutter_conditionred_RadarRenderer_changeAlpha
  (JNIEnv *, jclass, jshort);

/*
 * Class:     me_mattsutter_conditionred_RadarRenderer
 * Method:    addFrame
 * Signature: (Lme/mattsutter/conditionred/products/PaintArray;[[BI)V
 */
JNIEXPORT void JNICALL Java_me_mattsutter_conditionred_RadarRenderer_addFrame
  (JNIEnv *, jclass, jobject, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
